// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs -- -Iinclude template.go

package windows

const (
	OPERATION_RESOLVE_HELPER                 OperationID = 0x0
	OPERATION_RESOLVE_MAP                    OperationID = 0x1
	OPERATION_CREATE_PROGRAM                 OperationID = 0x2
	OPERATION_CREATE_MAP                     OperationID = 0x3
	OPERATION_LOAD_CODE                      OperationID = 0x4
	OPERATION_MAP_FIND_ELEMENT               OperationID = 0x5
	OPERATION_MAP_UPDATE_ELEMENT             OperationID = 0x6
	OPERATION_MAP_UPDATE_ELEMENT_WITH_HANDLE OperationID = 0x7
	OPERATION_MAP_DELETE_ELEMENT             OperationID = 0x8
	OPERATION_MAP_GET_NEXT_KEY               OperationID = 0x9
	OPERATION_QUERY_PROGRAM_INFO             OperationID = 0xa
	OPERATION_UPDATE_PINNING                 OperationID = 0xb
	OPERATION_GET_PINNED_OBJECT              OperationID = 0xc
	OPERATION_LINK_PROGRAM                   OperationID = 0xd
	OPERATION_UNLINK_PROGRAM                 OperationID = 0xe
	OPERATION_CLOSE_HANDLE                   OperationID = 0xf
	OPERATION_GET_EC_FUNCTION                OperationID = 0x10
	OPERATION_GET_PROGRAM_INFO               OperationID = 0x11
	OPERATION_GET_PINNED_MAP_INFO            OperationID = 0x12
	OPERATION_GET_LINK_HANDLE_BY_ID          OperationID = 0x13
	OPERATION_GET_MAP_HANDLE_BY_ID           OperationID = 0x14
	OPERATION_GET_PROGRAM_HANDLE_BY_ID       OperationID = 0x15
	OPERATION_GET_NEXT_LINK_ID               OperationID = 0x16
	OPERATION_GET_NEXT_MAP_ID                OperationID = 0x17
	OPERATION_GET_NEXT_PROGRAM_ID            OperationID = 0x18
	OPERATION_GET_OBJECT_INFO                OperationID = 0x19
	OPERATION_GET_NEXT_PINNED_PROGRAM_PATH   OperationID = 0x1a
	OPERATION_BIND_MAP                       OperationID = 0x1b
	OPERATION_RING_BUFFER_MAP_QUERY_BUFFER   OperationID = 0x1c
	OPERATION_RING_BUFFER_MAP_ASYNC_QUERY    OperationID = 0x1d
	OPERATION_LOAD_NATIVE_MODULE             OperationID = 0x1e
	OPERATION_LOAD_NATIVE_PROGRAMS           OperationID = 0x1f
	OPERATION_PROGRAM_TEST_RUN               OperationID = 0x20
	OPERATION_MAP_UPDATE_ELEMENT_BATCH       OperationID = 0x21
	OPERATION_MAP_DELETE_ELEMENT_BATCH       OperationID = 0x22
	OPERATION_MAP_GET_NEXT_KEY_VALUE_BATCH   OperationID = 0x23
)

type OperationID uint32

type OperationHeader struct {
	Length uint16
	Id     uint32
}

type MapDefinition struct {
	Type         uint32
	Key_size     uint32
	Value_size   uint32
	Max_entries  uint32
	Inner_map_id uint32
	Pinning      uint32
}

type CreateMapRequest struct {
	Header              OperationHeader
	Ebpf_map_definition MapDefinition
	Inner_map_handle    int64
}

type CreateMapReply struct {
	Header OperationHeader
	Handle int64
}

type MapFindElementRequest struct {
	Header     OperationHeader
	Handle     int64
	And_delete bool
	Key        [0]uint8
	Pad_cgo_0  [7]byte
}

type MapFindElementReply struct {
	Header OperationHeader
}

type MapUpdateElementRequest struct {
	Header    OperationHeader
	Handle    int64
	Option    uint32
	Data      [0]uint8
	Pad_cgo_0 [4]byte
}

type MapUpdateElementWithHandleRequest struct {
	Header       OperationHeader
	Map_handle   int64
	Value_handle int64
	Option       uint32
	Key          [0]uint8
	Pad_cgo_0    [4]byte
}

type MapDeleteElementRequest struct {
	Header OperationHeader
	Handle int64
}

type MapGetNextKeyRequest struct {
	Header OperationHeader
	Handle int64
}

type MapGetNextKeyReply struct {
	Header OperationHeader
	Handle int64
}

type UpdatePinningRequest struct {
	Header OperationHeader
	Handle int64
}

type GetPinnedObjectRequest struct {
	Header OperationHeader
}

type GetPinnedObjectReply struct {
	Header OperationHeader
	Handle int64
}

type LinkProgramRequest struct {
	Header         OperationHeader
	Program_handle int64
	Attach_type    GUID
}

type LinkProgramReply struct {
	Header OperationHeader
	Handle int64
}

type GetHandleByIdRequest struct {
	Header OperationHeader
	Id     uint32
}

type GetHandleByIdReply struct {
	Header OperationHeader
	Handle int64
}

type LoadNativeModuleRequest struct {
	Header OperationHeader
	Id     GUID
}

type LoadNativeModuleReply struct {
	Header               OperationHeader
	Native_module_handle int64
	Count_of_maps        uint64
	Count_of_programs    uint64
}

type LoadNativeProgramsRequest struct {
	Header OperationHeader
	Id     GUID
}

type LoadNativeProgramsReply struct {
	Header               OperationHeader
	Program_handle_count uint64
	Map_handle_count     uint64
}

type GetObjectInfoRequest struct {
	Header OperationHeader
	Handle int64
}

type GetObjectInfoReply struct {
	Header OperationHeader
}

type GetNextIdRequest struct {
	Header OperationHeader
	Id     uint32
}

type GetNextIdReply struct {
	Header OperationHeader
	Id     uint32
}

type BindMapRequest struct {
	Header         OperationHeader
	Program_handle int64
	Map_handle     int64
}

type ProgramTestRunRequest struct {
	Header         OperationHeader
	Program_handle int64
	Repeat_count   uint64
	Flags          uint32
	Cpu            uint32
	Batch_size     uint64
	Context_offset uint16
	Data           [0]uint8
	Pad_cgo_0      [6]byte
}

type ProgramTestRunReply struct {
	Header         OperationHeader
	Duration       uint64
	Return_value   uint64
	Context_offset uint64
}

type MapInfo struct {
	Id                uint32
	Type              uint32
	Key_size          uint32
	Value_size        uint32
	Max_entries       uint32
	Name              [64]int8
	Map_flags         uint32
	Inner_map_id      uint32
	Pinned_path_count uint32
}

type ProgramInfo struct {
	Id                uint32
	Type              uint32
	Nr_map_ids        uint32
	Map_ids           uint64
	Name              [64]int8
	Type_uuid         GUID
	Attach_type_uuid  GUID
	Pinned_path_count uint32
	Link_count        uint32
}
